name: push config - patch prod compare dev to dev
on:
  workflow_dispatch:

jobs:
  update_repo:
    name: push config - patch prod compare dev to dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: import config to prod
        run: CID=${{ vars.CLOUDENTITY_PROD_MIGRATIONPROD_SYSTEM_CID }} CS=${{ secrets.CLOUDENTITY_PROD_MIGRATIONPROD_SYSTEM_CS }} URL=${{ vars.CLOUDENTITY_PROD_MIGRATIONPROD_URL }} TENANT=${{ vars.CLOUDENTITY_PROD_MIGRATIONPROD_TENANT }} WORKSPACE=${{ vars.CLOUDENTITY_PROD_MIGRATIONPROD_WORKSPACE }}  ./scripts/push_config.sh scenarios/patch-prod-compare-dev-to-dev/patch.json
        shell: bash
